"""create_initial_clickwrap_models

Revision ID: afc3f2694ab1
Revises: 
Create Date: 2026-07-07 10:13:39.988101+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afc3f2694ab1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pg_trgm required for GIN trigram indexes on name_slug (packet, agreement_version).
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agreement',
    sa.Column('url_slug', sa.String(length=100), nullable=True),
    sa.Column('header_code', sa.Text(), nullable=True, comment='Custom HTML injected into the agreement header'),
    sa.Column('footer_code', sa.Text(), nullable=True, comment='Custom HTML injected into the agreement footer'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_org_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_org_user_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_by_org_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('agreement_url_slug_unique_per_workspace', 'agreement', ['workspace_id', 'url_slug'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('domain_setting',
    sa.Column('custom_domain', sa.String(length=50), nullable=True),
    sa.Column('custom_domain_status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('default_domain', sa.String(length=50), nullable=False, comment='Set by the service from settings.CLUSTER_ID on creation. Format: clickwrap.{cluster_id}.spotdraft.com'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_org_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_org_user_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_by_org_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('domain_setting_custom_domain_idx', 'domain_setting', ['custom_domain'], unique=False)
    op.create_index('domain_setting_custom_domain_unique_per_workspace', 'domain_setting', ['workspace_id', 'custom_domain'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('domain_setting_workspace_idx', 'domain_setting', ['workspace_id'], unique=False)
    op.create_table('legal_hub',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url_slug', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False, comment="Renamed from Django's `default` field (reserved word)"),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_org_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_org_user_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_by_org_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('legal_hub_name_idx', 'legal_hub', ['name'], unique=False)
    # Django uses Lower(F("name")) — case-insensitive unique per workspace.
    op.execute(
        """
        CREATE UNIQUE INDEX legal_hub_name_unique_per_workspace
        ON legal_hub (lower(name), workspace_id)
        WHERE is_deleted = false
        """
    )
    op.create_index('legal_hub_one_default_per_workspace', 'legal_hub', ['workspace_id'], unique=True, postgresql_where=sa.text('is_deleted = false AND is_default = true'))
    op.create_index('legal_hub_slug_unique_per_workspace', 'legal_hub', ['workspace_id', 'url_slug'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('legal_hub_url_slug_idx', 'legal_hub', ['url_slug'], unique=False)
    op.create_table('packet_settings',
    sa.Column('agreement_ui_type', sa.String(length=50), server_default='SINGLE_CHECKBOX', nullable=False, comment='Maps ClickwrapType — controls SDK presentation'),
    sa.Column('clickwrap_texts', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('whitelisted_domains', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('show_audit_click_status', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('send_executed_audit_email', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('allow_all_domains', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_org_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_org_user_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_by_org_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whitelabel_config',
    sa.Column('company_logo', sa.Text(), nullable=False, comment='GCS object path for company logo'),
    sa.Column('logo_redirect_url', sa.Text(), nullable=True),
    sa.Column('custom_styles', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='Brand CSS overrides e.g. primary_color'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('header_text', sa.String(length=100), nullable=True),
    sa.Column('brand_name', sa.String(length=100), nullable=True),
    sa.Column('add_footer', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_dropdown_and_download', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_published_agreements', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('favicon_icon', sa.Text(), nullable=True, comment='GCS object path for favicon (.ico)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_org_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_org_user_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_by_org_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('whitelabel_config_unique_per_workspace', 'whitelabel_config', ['workspace_id'], unique=True, postgresql_where=sa.text('is_active = true AND is_deleted = false'))
    op.create_index('whitelabel_config_workspace_is_active_idx', 'whitelabel_config', ['workspace_id', 'is_active'], unique=False)
    op.create_table('agreement_version',
    sa.Column('agreement_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True, comment='AgreementVersionStatus: DRAFT | PUBLISHED | PAST_PUBLISHED'),
    sa.Column('source', sa.String(length=10), server_default='EDITOR', nullable=False, comment='AgreementVersionSource: EDIT | EDITOR | UPLOAD'),
    sa.Column('html_content', sa.String(length=1000), nullable=True, comment='GCS object path for the HTML version file'),
    sa.Column('pdf_document', sa.String(length=1000), nullable=True, comment='GCS object path for the PDF version file'),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('sub_version_number', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('modified_by_org_user_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by_org_user_id', sa.BigInteger(), nullable=True),
    sa.Column('is_re_acceptance_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_org_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_org_user_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_by_org_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('agreement_version_name_slug_gin_idx', 'agreement_version', ['name_slug'], unique=False, postgresql_using='gin', postgresql_ops={'name_slug': 'gin_trgm_ops'})
    op.create_index('agreement_version_unique_draft_per_agreement', 'agreement_version', ['agreement_id'], unique=True, postgresql_where=sa.text("status = 'DRAFT' AND is_deleted = false"))
    op.create_index('agreement_version_unique_published_per_agreement', 'agreement_version', ['agreement_id'], unique=True, postgresql_where=sa.text("status = 'PUBLISHED' AND is_deleted = false"))
    op.create_index('agreement_version_unique_version_number', 'agreement_version', ['version_number', 'sub_version_number', 'agreement_id'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('legal_hub_agreement_mapping',
    sa.Column('legal_hub_id', sa.BigInteger(), nullable=False),
    sa.Column('agreement_id', sa.BigInteger(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True, comment="Renamed from Django's `order` field (reserved SQL word)"),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_org_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_org_user_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_by_org_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreement.id'], ),
    sa.ForeignKeyConstraint(['legal_hub_id'], ['legal_hub.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('legal_hub_agreement_mapping_agreement_idx', 'legal_hub_agreement_mapping', ['agreement_id'], unique=False)
    op.create_index('legal_hub_agreement_mapping_hub_idx', 'legal_hub_agreement_mapping', ['legal_hub_id'], unique=False)
    op.create_index('legal_hub_agreement_mapping_unique', 'legal_hub_agreement_mapping', ['agreement_id', 'legal_hub_id'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('packet',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('public_id', sa.UUID(), nullable=False, comment='Stable public identifier exposed to SDK callers'),
    sa.Column('packet_settings_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_by_org_user_at', sa.DateTime(timezone=True), nullable=True, comment='Last time an org user explicitly saved changes'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_org_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_org_user_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_by_org_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['packet_settings_id'], ['packet_settings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('packet_settings_id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('packet_name_slug_gin_idx', 'packet', ['name_slug'], unique=False, postgresql_using='gin', postgresql_ops={'name_slug': 'gin_trgm_ops'})
    op.create_index('packet_name_unique_per_workspace', 'packet', ['workspace_id', 'name_slug'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('packet_workspace_idx', 'packet', ['workspace_id'], unique=False)
    op.create_table('legal_hub_custom_url_mapping',
    sa.Column('custom_uri', sa.String(length=100), nullable=False),
    sa.Column('legal_hub_agreement_mapping_id', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_org_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_org_user_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_by_org_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['legal_hub_agreement_mapping_id'], ['legal_hub_agreement_mapping.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('legal_hub_custom_url_mapping_uri_idx', 'legal_hub_custom_url_mapping', ['custom_uri'], unique=False)
    op.create_index('legal_hub_custom_url_unique_per_agreement', 'legal_hub_custom_url_mapping', ['custom_uri', 'legal_hub_agreement_mapping_id'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('packet_agreement_mapping',
    sa.Column('packet_id', sa.BigInteger(), nullable=False),
    sa.Column('agreement_id', sa.BigInteger(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_org_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_org_user_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_by_org_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreement.id'], ),
    sa.ForeignKeyConstraint(['packet_id'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('packet_agreement_mapping_agreement_idx', 'packet_agreement_mapping', ['agreement_id'], unique=False)
    op.create_index('packet_agreement_mapping_packet_idx', 'packet_agreement_mapping', ['packet_id'], unique=False)
    op.create_index('packet_agreement_mapping_unique', 'packet_agreement_mapping', ['packet_id', 'agreement_id'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('packet_agreement_mapping_unique', table_name='packet_agreement_mapping', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('packet_agreement_mapping_packet_idx', table_name='packet_agreement_mapping')
    op.drop_index('packet_agreement_mapping_agreement_idx', table_name='packet_agreement_mapping')
    op.drop_table('packet_agreement_mapping')
    op.drop_index('legal_hub_custom_url_unique_per_agreement', table_name='legal_hub_custom_url_mapping', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('legal_hub_custom_url_mapping_uri_idx', table_name='legal_hub_custom_url_mapping')
    op.drop_table('legal_hub_custom_url_mapping')
    op.drop_index('packet_workspace_idx', table_name='packet')
    op.drop_index('packet_name_unique_per_workspace', table_name='packet', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('packet_name_slug_gin_idx', table_name='packet', postgresql_using='gin', postgresql_ops={'name_slug': 'gin_trgm_ops'})
    op.drop_table('packet')
    op.drop_index('legal_hub_agreement_mapping_unique', table_name='legal_hub_agreement_mapping', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('legal_hub_agreement_mapping_hub_idx', table_name='legal_hub_agreement_mapping')
    op.drop_index('legal_hub_agreement_mapping_agreement_idx', table_name='legal_hub_agreement_mapping')
    op.drop_table('legal_hub_agreement_mapping')
    op.drop_index('agreement_version_unique_version_number', table_name='agreement_version', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('agreement_version_unique_published_per_agreement', table_name='agreement_version', postgresql_where=sa.text("status = 'PUBLISHED' AND is_deleted = false"))
    op.drop_index('agreement_version_unique_draft_per_agreement', table_name='agreement_version', postgresql_where=sa.text("status = 'DRAFT' AND is_deleted = false"))
    op.drop_index('agreement_version_name_slug_gin_idx', table_name='agreement_version', postgresql_using='gin', postgresql_ops={'name_slug': 'gin_trgm_ops'})
    op.drop_table('agreement_version')
    op.drop_index('whitelabel_config_workspace_is_active_idx', table_name='whitelabel_config')
    op.drop_index('whitelabel_config_unique_per_workspace', table_name='whitelabel_config', postgresql_where=sa.text('is_active = true AND is_deleted = false'))
    op.drop_table('whitelabel_config')
    op.drop_table('packet_settings')
    op.drop_index('legal_hub_url_slug_idx', table_name='legal_hub')
    op.drop_index('legal_hub_slug_unique_per_workspace', table_name='legal_hub', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('legal_hub_one_default_per_workspace', table_name='legal_hub', postgresql_where=sa.text('is_deleted = false AND is_default = true'))
    op.drop_index('legal_hub_name_unique_per_workspace', table_name='legal_hub')
    op.drop_index('legal_hub_name_idx', table_name='legal_hub')
    op.drop_table('legal_hub')
    op.drop_index('domain_setting_workspace_idx', table_name='domain_setting')
    op.drop_index('domain_setting_custom_domain_unique_per_workspace', table_name='domain_setting', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('domain_setting_custom_domain_idx', table_name='domain_setting')
    op.drop_table('domain_setting')
    op.drop_index('agreement_url_slug_unique_per_workspace', table_name='agreement', postgresql_where=sa.text('is_deleted = false'))
    op.drop_table('agreement')
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    # ### end Alembic commands ###
